### PR TITLE
Add message when an user registers his/her email

### LINKED ISSUE #26: Update the email component
image

Update it to show a message instead of the component that reads:

```
Thanks for registering
```

And a little link to close out of it.

### PR DESCRIPTION
**Pull request by jdalzatec**
Fixes #26

### CODE REVIEW

**Comment by odarbelaeze** [comment]
Might you be kind enough to include a screenshot.

**Comment by jdalzatec** [comment]
Before: 
image

After:
image

**Comment by odarbelaeze** [comment]
image

Can you try this design instead @jdalzatec these green colors are "just a guide to the eye"

**Comment by jdalzatec** [comment]
What do you think about this ?

image

**Comment by jdalzatec** [comment]
image

**Pull request merged**
